import { CourseRecord } from "./store";

export const FULL_COURSE_TEST_RECORDS: CourseRecord[] = [
  // ── 高等数学/微积分 ──────────────────────────────────────────
  {
    id: "test-calc-001",
    date: "2026-05-20 09:00",
    subject: "高等数学/微积分",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始高等数学考核。第一题：请叙述极限的ε-δ定义。" },
      { role: "user", content: "对任意ε>0，存在δ>0，当0<|x-x0|<δ时，|f(x)-L|<ε，则极限为L。" },
      { role: "assistant", content: "正确。追问：洛必达法则的适用条件是什么？" },
      { role: "user", content: "0/0或∞/∞型不定式，且导数存在。" },
      { role: "assistant", content: "下一题：泰勒公式的一般形式是什么？" },
      { role: "user", content: "泰勒公式就是把函数用多项式展开，带个余项...具体公式记不太清了。" },
      { role: "assistant", content: "好，接下来：定积分的换元法步骤是什么？" },
      { role: "user", content: "令x=φ(t)，dx=φ'(t)dt，上下限也要随之变换，最后对t积分。" },
      { role: "assistant", content: "接下来考察多元函数。偏导数与全微分的关系是什么？" },
      { role: "user", content: "偏导数存在不一定可微，但可微一定有偏导数，且全微分dz=∂z/∂x·dx+∂z/∂y·dy。" },
      { role: "assistant", content: "最后：常数项级数收敛的必要条件是什么？" },
      { role: "user", content: "通项趋于0是必要条件，但不充分，比如调和级数。" },
    ],
    feedback: {
      summary: "极限与积分基础掌握扎实，泰勒公式记忆不够准确，其余知识点表现良好。",
      knowledge_results: [
        {
          point: "极限与连续",
          status: "mastered",
          score: 92,
          detail: "ε-δ定义表述规范准确，洛必达法则条件补充完整。",
          expression_advice: "可以补充说明分母导数不为零的条件，更严谨。",
          suggested_answer: "极限 $\\lim_{x\\to x_0}f(x)=L$ 的 $\\varepsilon$-$\\delta$ 定义：\n\n对任意 $\\varepsilon > 0$，存在 $\\delta > 0$，当 $0 < |x - x_0| < \\delta$ 时，有 $|f(x) - L| < \\varepsilon$。\n\n洛必达法则适用条件：$\\frac{0}{0}$ 或 $\\frac{\\infty}{\\infty}$ 型，且 $f'(x)/g'(x)$ 的极限存在，且 $g'(x)\\neq 0$。",
          wrong_answer_summary: "",
        },
        {
          point: "一元函数微分",
          status: "weak",
          score: 48,
          detail: "泰勒公式只能给出概念性描述，无法写出正确形式。",
          expression_advice: "回答公式类问题时应直接写出公式，不要用「大概」等模糊表述。",
          suggested_answer: "泰勒公式（带 Peano 余项）：\n\n$$f(x) = \\sum_{n=0}^{N} \\frac{f^{(n)}(x_0)}{n!}(x-x_0)^n + o\\bigl((x-x_0)^N\\bigr)$$\n\n带 Lagrange 余项：\n\n$$f(x) = \\sum_{n=0}^{N} \\frac{f^{(n)}(x_0)}{n!}(x-x_0)^n + \\frac{f^{(N+1)}(\\xi)}{(N+1)!}(x-x_0)^{N+1}$$\n\n其中 $\\xi$ 在 $x_0$ 与 $x$ 之间。",
          wrong_answer_summary: "学生只能描述概念（函数展开为多项式），无法给出带公式的完整表述。",
        },
        {
          point: "一元函数积分",
          status: "mastered",
          score: 85,
          detail: "换元法步骤描述清晰，上下限变换提及正确。",
          expression_advice: "可以补充说明 φ(t) 需单调可微，以确保换元合法。",
          suggested_answer: "定积分换元法：令 $x = \\varphi(t)$，则\n\n$$\\int_a^b f(x)\\,dx = \\int_{\\alpha}^{\\beta} f(\\varphi(t))\\,\\varphi'(t)\\,dt$$\n\n其中 $\\alpha, \\beta$ 满足 $\\varphi(\\alpha)=a,\\ \\varphi(\\beta)=b$，且 $\\varphi'(t)$ 连续不变号。",
          wrong_answer_summary: "",
        },
        {
          point: "多元函数微分",
          status: "mastered",
          score: 88,
          detail: "偏导与全微分关系阐述准确，举例说明了不充分性。",
          expression_advice: "表述完整，可以进一步补充连续偏导数可微的充分条件。",
          suggested_answer: "若 $z=f(x,y)$ 在点 $(x_0,y_0)$ 可微，则全微分为\n\n$$dz = \\frac{\\partial z}{\\partial x}dx + \\frac{\\partial z}{\\partial y}dy$$\n\n偏导数存在 $\\not\\Rightarrow$ 可微；连续偏导数 $\\Rightarrow$ 可微。",
          wrong_answer_summary: "",
        },
        {
          point: "级数",
          status: "mastered",
          score: 90,
          detail: "必要条件与反例（调和级数）均指出，思维严谨。",
          expression_advice: "回答简洁有力，可继续补充充分条件（比较判别法、比值法等）。",
          suggested_answer: "收敛必要条件：$\\lim_{n\\to\\infty} a_n = 0$（通项趋于0）。\n\n反例：调和级数 $\\sum_{n=1}^\\infty \\frac{1}{n}$ 发散，尽管 $\\frac{1}{n}\\to 0$。",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 81,
      weak_points: ["一元函数微分"],
      expression_summary: "整体答题流畅，极限和积分部分表达规范；泰勒公式回答过于口语化，缺乏公式支撑，建议加强数学符号书写能力。",
      next_focus: "重点复习泰勒展开各知识点（含麦克劳林展开）及其在极限计算中的应用，补充微分方程基础。",
    },
  },

  // ── 线性代数 ─────────────────────────────────────────────────
  {
    id: "test-la-001",
    date: "2026-05-20 10:30",
    subject: "线性代数",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始线性代数考核。矩阵的秩的定义是什么？" },
      { role: "user", content: "矩阵的秩是矩阵中最高阶非零子式的阶数，等于行阶梯形中非零行的数目。" },
      { role: "assistant", content: "很好。如何判断矩阵可逆？" },
      { role: "user", content: "方阵可逆当且仅当行列式不为零，等价于满秩。" },
      { role: "assistant", content: "特征值和特征向量的定义？" },
      { role: "user", content: "Av=λv，v非零向量，λ是特征值，v是对应特征向量。" },
      { role: "assistant", content: "如何求矩阵的特征值？" },
      { role: "user", content: "解特征方程det(A-λI)=0，得到λ，再代入(A-λI)v=0求特征向量。" },
      { role: "assistant", content: "实对称矩阵有什么重要性质？" },
      { role: "user", content: "实对称矩阵的特征值全为实数，不同特征值对应的特征向量正交，一定可以正交对角化。" },
      { role: "assistant", content: "二次型的标准形是什么？如何化简？" },
      { role: "user", content: "通过正交变换x=Py，P是由特征向量构成的正交矩阵，可以将二次型化为标准形Σλᵢyᵢ²。" },
    ],
    feedback: {
      summary: "线性代数核心概念掌握扎实，特征值理论和二次型均能正确阐述，表现优秀。",
      knowledge_results: [
        {
          point: "矩阵运算",
          status: "mastered",
          score: 92,
          detail: "秩的定义和可逆判定完整准确，两种等价表述都提及。",
          expression_advice: "可以补充利用初等行变换求秩的具体步骤，让回答更完整。",
          suggested_answer: "矩阵的秩 $r(A)$：$A$ 中不为零的子式的最高阶数。等价地，行阶梯形中非零行的个数。\n\n可逆条件（等价）：$|A|\\neq 0$ $\\Leftrightarrow$ $r(A)=n$ $\\Leftrightarrow$ $A$ 的行（列）向量组线性无关。",
          wrong_answer_summary: "",
        },
        {
          point: "行列式",
          status: "mastered",
          score: 90,
          detail: "结合行列式与秩来判断可逆性，理解透彻。",
          expression_advice: "答题清晰简洁，表达规范。",
          suggested_answer: "方阵 $A$ 可逆 $\\Leftrightarrow$ $\\det(A) \\neq 0$。\n\n$n$ 阶行列式按第 $i$ 行展开：$|A| = \\sum_{j=1}^n a_{ij}A_{ij}$，其中 $A_{ij}=(-1)^{i+j}M_{ij}$。",
          wrong_answer_summary: "",
        },
        {
          point: "特征值与特征向量",
          status: "mastered",
          score: 95,
          detail: "特征方程、特征向量求法以及实对称矩阵性质全部正确，回答出色。",
          expression_advice: "实对称矩阵性质表述准确完整，值得肯定。",
          suggested_answer: "特征方程：$\\det(A - \\lambda I) = 0$，解出 $\\lambda$。\n\n特征向量：对每个 $\\lambda_i$，解齐次方程组 $(A-\\lambda_i I)\\mathbf{v}=\\mathbf{0}$。\n\n实对称矩阵：① 特征值均为实数；② 不同特征值的特征向量正交；③ 必可正交对角化，即存在正交矩阵 $P$ 使 $P^TAP=\\Lambda=\\mathrm{diag}(\\lambda_1,\\ldots,\\lambda_n)$。",
          wrong_answer_summary: "",
        },
        {
          point: "二次型",
          status: "mastered",
          score: 90,
          detail: "正交变换化标准形思路清晰，$P$ 构造正确。",
          expression_advice: "可以进一步说明正惯性指数和负惯性指数的概念，以及正定条件。",
          suggested_answer: "二次型 $f=\\mathbf{x}^T A \\mathbf{x}$（$A$ 为实对称矩阵）。\n\n正交变换化标准形：令 $\\mathbf{x}=P\\mathbf{y}$，$P$ 为正交矩阵（列为 $A$ 的单位化特征向量），则\n\n$$f = \\lambda_1 y_1^2 + \\lambda_2 y_2^2 + \\cdots + \\lambda_n y_n^2$$\n\n正定条件：所有特征值 $\\lambda_i > 0$，等价于各阶顺序主子式均大于零。",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 92,
      weak_points: [],
      expression_summary: "答题逻辑严谨，数学术语使用规范，各知识点均能给出定义与等价描述，建议在口头表达时适当增加板书/公式说明的习惯。",
      next_focus: "可进一步练习向量空间和线性变换的抽象定义，以及SVD分解，提升综合能力。",
    },
  },

  // ── 概率论与数理统计 ────────────────────────────────────────
  {
    id: "test-prob-001",
    date: "2026-05-20 14:00",
    subject: "概率论与数理统计",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始概率论考核。条件概率的定义是什么？" },
      { role: "user", content: "P(A|B)=P(AB)/P(B)，在B已发生的条件下A发生的概率。" },
      { role: "assistant", content: "贝叶斯公式是什么？" },
      { role: "user", content: "P(Bi|A) = P(A|Bi)P(Bi) / ΣP(A|Bj)P(Bj)，用于已知先验求后验概率。" },
      { role: "assistant", content: "正态分布的密度函数是什么形式？" },
      { role: "user", content: "f(x) = 1/(σ√2π) · exp(-(x-μ)²/2σ²)，μ是均值，σ²是方差。" },
      { role: "assistant", content: "大数定律和中心极限定理有什么区别？" },
      { role: "user", content: "大数定律说样本均值以概率收敛到期望；中心极限定理说大样本下均值的分布近似正态，关注的是分布而非收敛。" },
      { role: "assistant", content: "点估计有哪些方法？" },
      { role: "user", content: "矩估计法和最大似然估计法。矩估计用样本矩代替总体矩，最大似然是极大化似然函数。" },
    ],
    feedback: {
      summary: "概率论基础扎实，大数定律与中心极限定理区别理解到位，参数估计方法均能阐述。",
      knowledge_results: [
        {
          point: "概率基础",
          status: "mastered",
          score: 95,
          detail: "条件概率和贝叶斯公式均准确无误，分子分母清晰。",
          expression_advice: "可以补充全概率公式与贝叶斯的关系，表述更系统。",
          suggested_answer: "条件概率：$P(A|B) = \\dfrac{P(AB)}{P(B)},\\quad P(B)>0$。\n\n贝叶斯公式（$B_1,\\ldots,B_n$ 为完备事件组）：\n\n$$P(B_i|A) = \\frac{P(A|B_i)P(B_i)}{\\displaystyle\\sum_{j=1}^n P(A|B_j)P(B_j)}$$",
          wrong_answer_summary: "",
        },
        {
          point: "随机变量与分布",
          status: "mastered",
          score: 90,
          detail: "正态分布密度函数书写正确，参数含义清晰。",
          expression_advice: "可进一步指出标准化变换 $Z=(X-\\mu)/\\sigma\\sim N(0,1)$ 的重要性。",
          suggested_answer: "正态分布 $X\\sim N(\\mu, \\sigma^2)$ 的密度函数：\n\n$$f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\exp\\!\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right), \\quad -\\infty < x < +\\infty$$\n\n标准化：令 $Z = \\dfrac{X-\\mu}{\\sigma}$，则 $Z\\sim N(0,1)$。",
          wrong_answer_summary: "",
        },
        {
          point: "大数定律与中心极限定理",
          status: "mastered",
          score: 93,
          detail: "两者的区别（收敛性 vs 分布近似）阐述准确，思维清晰。",
          expression_advice: "回答很好，可以加入具体定理名称（辛钦大数定律、Lindeberg-Lévy定理）。",
          suggested_answer: "**辛钦大数定律**：$X_1,\\ldots,X_n$ i.i.d.，$E[X_i]=\\mu$，则 $\\bar{X}_n\\xrightarrow{P}\\mu$。\n\n**中心极限定理（Lindeberg-Lévy）**：i.i.d.，$E[X_i]=\\mu,\\ D[X_i]=\\sigma^2$，则\n\n$$\\frac{\\bar{X}_n-\\mu}{\\sigma/\\sqrt{n}} \\xrightarrow{d} N(0,1)$$",
          wrong_answer_summary: "",
        },
        {
          point: "参数估计",
          status: "mastered",
          score: 85,
          detail: "矩估计和最大似然估计均能概括，但MLE的优良性未提及。",
          expression_advice: "可以补充MLE的优良性（相合性、渐近有效性）以及无偏估计的概念。",
          suggested_answer: "**矩估计**：用样本 $k$ 阶矩 $\\hat{\\mu}_k = \\frac{1}{n}\\sum X_i^k$ 代替总体矩 $E[X^k]$，解出参数。\n\n**最大似然估计**：极大化似然函数 $L(\\theta) = \\prod_{i=1}^n f(x_i;\\theta)$，等价于极大化 $\\ln L$，解方程 $\\frac{d\\ln L}{d\\theta}=0$。\n\nMLE 具有相合性和不变性，大样本下渐近正态且渐近有效。",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 91,
      weak_points: [],
      expression_summary: "各知识点表达准确规范，大数定律与中心极限定理的辨析尤其清晰；建议养成给出定理名称的习惯，增加回答的专业感。",
      next_focus: "进一步练习假设检验（t检验、χ²检验）和区间估计，以及随机过程基础。",
    },
  },

  // ── 数据结构 ─────────────────────────────────────────────────
  {
    id: "test-ds-001",
    date: "2026-05-21 09:00",
    subject: "数据结构",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始数据结构考核。二叉树的遍历方式有哪些？" },
      { role: "user", content: "前序（根左右）、中序（左根右）、后序（左右根）和层序遍历。" },
      { role: "assistant", content: "二叉搜索树的时间复杂度是多少？" },
      { role: "user", content: "平均O(log n)，最坏O(n)（退化为链表）。" },
      { role: "assistant", content: "快速排序的时间复杂度和最坏情况？" },
      { role: "user", content: "平均O(n log n)，最坏O(n²)，当每次选的pivot都是最大或最小值时退化。" },
      { role: "assistant", content: "哈希表的冲突解决方法有哪些？" },
      { role: "user", content: "链地址法和开放定址法（线性探测、二次探测、双哈希）。" },
      { role: "assistant", content: "图的BFS和DFS的时间复杂度是多少？" },
      { role: "user", content: "用邻接表是O(V+E)，用邻接矩阵是O(V²)。" },
    ],
    feedback: {
      summary: "数据结构基础扎实，各常见结构和算法的复杂度掌握准确，图算法理解到位。",
      knowledge_results: [
        {
          point: "树与二叉树",
          status: "mastered",
          score: 93,
          detail: "四种遍历方式均列出，BST复杂度平均和最坏情况均正确。",
          expression_advice: "可以补充AVL树或红黑树如何保证O(log n)最坏复杂度。",
          suggested_answer: "二叉树遍历：前序（根→左→右）、中序（左→根→右）、后序（左→右→根）、层序（BFS）。\n\nBST 操作复杂度：\n- 平均：$O(\\log n)$（平衡时）\n- 最坏：$O(n)$（退化为链表）\n\nAVL/红黑树保证 $O(\\log n)$ 最坏情况。",
          wrong_answer_summary: "",
        },
        {
          point: "排序算法",
          status: "mastered",
          score: 90,
          detail: "快排的复杂度和退化条件均正确，分析清晰。",
          expression_advice: "可以补充归并排序保证O(n log n)以及各排序算法的稳定性对比。",
          suggested_answer: "快速排序：\n- 平均：$O(n\\log n)$，最坏：$O(n^2)$（pivot 每次选到极值）\n- 空间：平均 $O(\\log n)$（递归栈）\n- 优化：随机化 pivot、三路划分\n\n各排序稳定性：归并排序✓、冒泡✓；快排✗、堆排序✗。",
          wrong_answer_summary: "",
        },
        {
          point: "哈希表",
          status: "mastered",
          score: 88,
          detail: "两大类冲突解决方法均提及，且子方法列举完整。",
          expression_advice: "可以补充负载因子和rehash的概念，增加回答的系统性。",
          suggested_answer: "冲突解决：\n1. **链地址法（Chaining）**：每个桶维护链表\n2. **开放定址法**：\n   - 线性探测：$h(k,i)=(h(k)+i)\\bmod m$\n   - 二次探测：$h(k,i)=(h(k)+c_1 i+c_2 i^2)\\bmod m$\n   - 双重散列：$h(k,i)=(h_1(k)+i\\cdot h_2(k))\\bmod m$\n\n负载因子 $\\alpha=n/m$，通常保持 $\\alpha<0.75$ 触发 rehash，均摊 $O(1)$。",
          wrong_answer_summary: "",
        },
        {
          point: "图",
          status: "mastered",
          score: 92,
          detail: "BFS/DFS复杂度与存储结构的关系回答准确，区分清晰。",
          expression_advice: "非常好，可以进一步讨论Dijkstra或拓扑排序的应用场景。",
          suggested_answer: "BFS/DFS 时间复杂度：\n- 邻接表：$O(V+E)$\n- 邻接矩阵：$O(V^2)$\n\nBFS 空间 $O(V)$（队列），DFS 空间 $O(V)$（栈/递归深度）。\n\nBFS 用于**最短路径**（无权图），DFS 用于**连通分量、拓扑排序**。",
          wrong_answer_summary: "",
        },
        {
          point: "线性表",
          status: "not_tested",
          score: 0,
          detail: "本次未考察该知识点。",
          expression_advice: "",
          suggested_answer: "",
          wrong_answer_summary: "",
        },
        {
          point: "栈与队列",
          status: "not_tested",
          score: 0,
          detail: "本次未考察该知识点。",
          expression_advice: "",
          suggested_answer: "",
          wrong_answer_summary: "",
        },
        {
          point: "查找算法",
          status: "not_tested",
          score: 0,
          detail: "本次未考察该知识点。",
          expression_advice: "",
          suggested_answer: "",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 91,
      weak_points: [],
      expression_summary: "数据结构各知识点表达准确，复杂度分析规范；建议在回答时养成主动补充优化方案和边界情况的习惯。",
      next_focus: "建议补充练习：线段树、并查集、Trie，以及动态规划与数据结构的结合题（如LRU缓存）。",
    },
  },

  // ── 操作系统 ─────────────────────────────────────────────────
  {
    id: "test-os-001",
    date: "2026-05-22 10:00",
    subject: "操作系统",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始操作系统考核。进程和线程的区别是什么？" },
      { role: "user", content: "进程是资源分配的基本单位，有独立的地址空间；线程是调度的基本单位，共享进程的资源，创建切换开销小。" },
      { role: "assistant", content: "死锁产生的四个必要条件是什么？" },
      { role: "user", content: "互斥、占有并等待、不可剥夺、循环等待，四个条件同时满足才会死锁。" },
      { role: "assistant", content: "虚拟内存的作用是什么？" },
      { role: "user", content: "把物理内存和磁盘结合起来，让进程可以使用比物理内存更大的地址空间，通过页面置换在两者之间调度页面。" },
      { role: "assistant", content: "LRU页面置换算法怎么实现？" },
      { role: "user", content: "可以用一个链表，每次访问把对应页移到头部，缺页时替换链表尾部；或者用哈希表+双向链表实现O(1)。" },
      { role: "assistant", content: "用户态和内核态的区别？什么时候切换？" },
      { role: "user", content: "用户态权限低不能执行特权指令，内核态权限最高。系统调用、中断、异常会切换到内核态。" },
    ],
    feedback: {
      summary: "操作系统核心概念掌握扎实，死锁四条件和虚拟内存阐述准确，LRU高效实现思路清晰。",
      knowledge_results: [
        {
          point: "进程与线程",
          status: "mastered",
          score: 92,
          detail: "进程和线程的区别从资源分配和调度两个维度清晰对比。",
          expression_advice: "可以补充协程（Coroutine）的概念，以及多线程的同步问题，增加深度。",
          suggested_answer: "进程：资源分配单位，独立地址空间，切换代价高（上下文含 PCB、页表等）。\n\n线程：调度单位，共享进程地址空间（代码、数据、文件），各自有独立栈和寄存器，切换快。\n\n关键区别：进程间通信（IPC）代价高；线程间通信可直接共享内存但需同步。",
          wrong_answer_summary: "",
        },
        {
          point: "进程同步",
          status: "not_tested",
          score: 0,
          detail: "死锁作为进程同步/互斥问题被考察，四个必要条件全部正确。",
          expression_advice: "可以进一步讨论银行家算法（死锁避免）或资源剥夺（死锁恢复）。",
          suggested_answer: "死锁四必要条件：①互斥、②占有并等待、③不可剥夺、④循环等待。\n\n预防：破坏其中一个条件（如资源有序分配破坏循环等待）。\n\n检测与恢复：资源分配图算法，回滚/终止进程。",
          wrong_answer_summary: "",
        },
        {
          point: "虚拟内存",
          status: "mastered",
          score: 90,
          detail: "虚拟内存作用和页面置换均能正确阐述，LRU的高效实现（哈希+链表）尤其突出。",
          expression_advice: "回答出色，可以进一步阐述TLB的作用以及缺页中断的处理流程。",
          suggested_answer: "虚拟内存：使进程地址空间 $\\gg$ 物理内存，通过**按需调页（demand paging）**实现。\n\nLRU 实现：\n- 哈希表（$O(1)$查找） + 双向链表（$O(1)$移动）\n- 访问时移到头部，驱逐时取尾部\n\n页面置换算法比较：OPT（最优，离线）$>$ LRU $>$ Clock $>$ FIFO（Belady异常）。",
          wrong_answer_summary: "",
        },
        {
          point: "内存管理",
          status: "mastered",
          score: 88,
          detail: "用户态/内核态区分正确，三种切换场景（系统调用、中断、异常）均列出。",
          expression_advice: "可以进一步阐述系统调用的完整流程（trap指令→内核栈→返回），更具体。",
          suggested_answer: "用户态：CPU 特权级低（Ring 3），不能执行特权指令（I/O、修改页表等）。\n内核态：CPU 特权级最高（Ring 0），可执行所有指令。\n\n切换触发：\n1. **系统调用**：用户主动（`syscall` / `int 0x80`）\n2. **硬件中断**：外设请求\n3. **异常**：缺页、除零等\n\n切换代价：保存用户上下文 → 切换至内核栈 → 处理 → 恢复现场。",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 90,
      weak_points: [],
      expression_summary: "操作系统各知识点表达准确，LRU实现的高效方案（哈希+双向链表）尤其体现了工程思维；建议补充文件系统和I/O相关内容。",
      next_focus: "补充练习：文件系统（inode、目录结构）、I/O多路复用（select/poll/epoll）以及内存分配器（伙伴系统、slab）。",
    },
  },

  // ── 综合测试（跨科目） ──────────────────────────────────────
  {
    id: "test-comp-001",
    date: "2026-05-23 14:00",
    subject: "综合测试",
    mode: "text",
    messages: [
      { role: "assistant", content: "开始综合考核，涵盖数学、数据结构和操作系统。第一题：矩阵乘法的时间复杂度是多少？" },
      { role: "user", content: "普通算法O(n³)，Strassen算法O(n^2.807)。" },
      { role: "assistant", content: "正态分布为什么在统计中那么重要？" },
      { role: "user", content: "因为中心极限定理保证了大样本均值近似正态，而且正态分布数学性质好（封闭性、只需均值和方差就能确定），很多检验方法都基于正态假设。" },
      { role: "assistant", content: "如何用栈实现括号匹配检查？" },
      { role: "user", content: "遍历字符串，遇到左括号入栈，遇到右括号出栈并检查是否匹配，最后栈为空则合法。时间O(n)，空间O(n)。" },
      { role: "assistant", content: "进程间通信（IPC）有哪些方式？各有什么特点？" },
      { role: "user", content: "管道（半双工、亲缘关系）、消息队列（有格式）、共享内存（最快、需同步）、信号量（同步用）、Socket（网络IPC）、信号（异步通知）。" },
    ],
    feedback: {
      summary: "综合能力出色，跨科目知识融合运用自如，各知识点均能给出准确且有深度的回答。",
      knowledge_results: [
        {
          point: "矩阵运算",
          status: "mastered",
          score: 90,
          detail: "矩阵乘法复杂度普通和Strassen算法均正确。",
          expression_advice: "可以进一步讨论实际工程中为何很少用Strassen（常数大、数值稳定性）。",
          suggested_answer: "朴素矩阵乘法：$T(n) = O(n^3)$（三重循环）\n\nStrassen：$T(n) = O(n^{\\log_2 7}) \\approx O(n^{2.807})$\n\n实际工程：BLAS 库利用 cache 局部性优化，常数远小于 Strassen，故 $n$ 不极大时 $O(n^3)$ 更快。",
          wrong_answer_summary: "",
        },
        {
          point: "大数定律与中心极限定理",
          status: "mastered",
          score: 95,
          detail: "中心极限定理的重要性从多角度（封闭性、参数少、检验基础）阐述，理解深刻。",
          expression_advice: "出色，可以提及非正态分布下的稳健方法（bootstrap等）。",
          suggested_answer: "正态分布在统计中的核心地位：\n1. **CLT**：$\\bar{X}_n \\xrightarrow{d} N(\\mu, \\sigma^2/n)$，大样本下普适\n2. **封闭性**：正态分布的线性组合仍正态 $N_1+N_2\\sim N(\\mu_1+\\mu_2,\\sigma_1^2+\\sigma_2^2)$\n3. **参数少**：仅 $\\mu,\\sigma^2$ 即可完全描述\n4. **检验**：$t$ 检验、$F$ 检验、$\\chi^2$ 检验均以正态为基础",
          wrong_answer_summary: "",
        },
        {
          point: "栈与队列",
          status: "mastered",
          score: 93,
          detail: "括号匹配算法思路清晰，时间和空间复杂度均正确分析。",
          expression_advice: "回答完整，可以补充如何扩展到多种括号（()、[]、{}）的匹配。",
          suggested_answer: "括号匹配算法：\n```python\ndef is_valid(s: str) -> bool:\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for c in s:\n        if c in '([{':\n            stack.append(c)\n        elif c in ')]}':\n            if not stack or stack[-1] != pairs[c]:\n                return False\n            stack.pop()\n    return len(stack) == 0\n```\n时间 $O(n)$，空间 $O(n)$。",
          wrong_answer_summary: "",
        },
        {
          point: "进程与线程",
          status: "mastered",
          score: 95,
          detail: "IPC六种方式全部列出，各特点精确概括，回答系统全面。",
          expression_advice: "非常出色，可以补充各IPC方式的适用场景（如共享内存用于高性能，消息队列用于解耦）。",
          suggested_answer: "进程间通信（IPC）方式：\n| 方式 | 特点 | 适用场景 |\n|------|------|----------|\n| 管道 | 半双工，亲缘进程 | 父子进程数据流 |\n| 命名管道 | 非亲缘进程 | 任意进程通信 |\n| 消息队列 | 有格式，存内核 | 解耦通信 |\n| 共享内存 | **最快**，需同步 | 高性能大数据量 |\n| 信号量 | 计数器，PV操作 | 同步与互斥 |\n| Socket | 支持跨主机 | 网络通信 |\n| 信号 | 异步通知 | 异常/事件通知 |",
          wrong_answer_summary: "",
        },
      ],
      overall_score: 93,
      weak_points: [],
      expression_summary: "综合测试表现优秀，能将不同学科知识有机结合；IPC部分答得尤为全面，体现了操作系统的系统性理解。",
      next_focus: "可以尝试综合应用题：如用操作系统原语实现并发数据结构，或用概率知识分析哈希冲突期望。",
    },
  },
];
