import { InterviewRecord } from "./store";

export const FULL_INTERVIEW_TEST_RECORDS: InterviewRecord[] = [
  {
    id: "test-interview-001",
    date: "2026-05-22 09:30",
    difficulty: "standard",
    mode: "text",
    questionsCount: 10,
    messages: [
      { role: "assistant", content: "你好！我是今天的面试官。请先做一个简短的自我介绍，重点介绍你的研究经历和申请动机。" },
      { role: "user", content: "老师您好，我是北京交通大学通信工程专业的张三，专业排名1/96，GPA 3.96/4.00。我的研究方向涵盖深度强化学习、光学器件设计与LLM Agent记忆架构，以第一/共一作者身份发表SCI论文2篇，第三作者发表ICML 2026论文1篇，曾两次获得国家奖学金。申请贵校是因为您的团队在深度学习方向的研究与我的经历高度契合。" },
      { role: "assistant", content: "很好，背景很扎实。你提到了ICML 2026的论文，能具体说说这个工作的核心创新点是什么吗？" },
      { role: "user", content: "我们提出了COIRL-AD框架，核心是将模仿学习（IL）与强化学习（RL）在Latent World Model中解耦，通过竞争机制让两个策略共享经验。这样IL负责安全驾驶行为的快速收敛，RL则通过探索寻找最优策略，两者互补。" },
      { role: "assistant", content: "这个竞争机制具体是怎么设计的？两个策略如何决定何时共享经验？" },
      { role: "user", content: "每个时间步，两个策略分别产生动作，根据TD误差或价值函数评估哪个策略在当前状态表现更好，表现更好的策略的经验会被优先加入共享缓冲区。这样在简单场景下IL主导，复杂场景下RL可以发挥更大作用。" },
      { role: "assistant", content: "你负责的长尾数据集实验，L2误差降低到0.71m，碰撞率0.09%，这些指标相比baseline提升了多少？" },
      { role: "user", content: "相比LAW基线，在子集1（L2误差大的样本）上L2误差从1.3m降到0.71m，降低了约45%；子集2（碰撞率高的样本）碰撞率从2.1%降到0.47%，降低了78%。在普通数据集上性能基本持平，说明我们的改进主要针对长尾场景有效。" },
      { role: "assistant", content: "很好，数据很有说服力。另一个工作是DOE光学设计，能解释一下SAC算法在这里是怎么发挥作用的吗？" },
      { role: "user", content: "传统衍射光学元件设计用迭代傅里叶变换算法，容易陷入局部最优。我们把分束设计建模为强化学习问题，状态是当前的衍射相位分布，动作是对相位的调整量，奖励是分束均匀性误差。SAC的最大熵框架鼓励探索，能跳出局部最优，最终分束均匀性误差低至0.46%，优于传统方法。" },
      { role: "assistant", content: "状态空间是怎么定义的？衍射相位是连续的高维空间，SAC如何处理这个问题？" },
      { role: "user", content: "我们对相位进行了离散化和压缩表示，将256×256的相位矩阵通过PCA降维到低维隐空间作为状态输入，同时动作空间也做了限制，每步只调整局部区域的相位值，这样有效降低了维度和探索空间的复杂度。" },
      { role: "assistant", content: "现在来一道算法题。请实现一个函数，给定一个整数数组，找出其中和为目标值target的两个数的索引。" },
      { role: "user", content: "用哈希表：遍历数组，对每个元素x，检查target-x是否在哈希表中，是则返回两个索引，否则将x和其索引存入哈希表。时间O(n)，空间O(n)。Python实现：\n\ndef two_sum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        if target - x in seen:\n            return [seen[target-x], i]\n        seen[x] = i\n    return []" },
      { role: "assistant", content: "很好！代码逻辑正确，复杂度分析也到位。最后，你有什么想问我的吗？" },
      { role: "user", content: "请问老师，您的研究组目前最关注哪个方向？我应该如何在入学前做一些预备工作？" },
    ],
    feedback: {
      summary: "候选人技术背景扎实，对两个核心研究项目的理解深刻，能清晰阐述创新点和量化指标。算法题一次AC，表现出色。整体面试表现优秀，强烈推荐录取。",
      questions: [
        {
          question: "自我介绍",
          answer: "简洁有力，三条亮点（排名、论文、奖学金）信息密度高",
          evaluation: "优秀——逻辑清晰，突出核心优势，时间控制恰当",
          expression_advice: "可以在最后加一句申请动机，让面试官了解你的研究方向匹配度。",
          suggested_answer: "自我介绍建议结构：院校+排名 → 核心研究方向 → 代表性成果（论文/奖项）→ 申请动机（1句）。控制在90-120秒。",
          score: 90,
        },
        {
          question: "ICML 2026论文核心创新点",
          answer: "清楚阐述了IL与RL解耦和竞争机制共享经验的核心思路",
          evaluation: "优秀——技术理解深入，表述逻辑清晰",
          expression_advice: "可以用一句话概括核心贡献的意义（解决了什么问题），更有感染力。",
          suggested_answer: "核心创新表述建议：'我们解决了IL易过拟合安全行为、RL收敛慢的互补问题，通过竞争机制实现在线动态经验共享，在长尾自动驾驶场景下取得了显著提升。'",
          score: 93,
        },
        {
          question: "竞争机制设计细节",
          answer: "用TD误差评估策略表现，好的策略经验优先入共享缓冲区",
          evaluation: "优秀——能回答到方法细节层面，工程意识强",
          expression_advice: "可以提及这种设计的局限性，展示批判性思维。",
          suggested_answer: "完整回答还应包括：边界情况处理（两策略TD误差相近时）、超参数（共享比例）的设置，以及与优先经验回放（PER）的关系。",
          score: 88,
        },
        {
          question: "长尾实验的量化指标",
          answer: "准确给出L2误差降低45%、碰撞率降低78%，与baseline对比清晰",
          evaluation: "出色——能给出量化对比数据，科研汇报能力强",
          expression_advice: "非常好，建议记住所有核心指标，面试中量化数据是最有说服力的。",
          suggested_answer: "回答量化结果时的建议格式：'相比 [baseline]，在 [场景/数据集] 上，[指标] 从 [X] 提升到 [Y]，提升幅度为 [Z%]，而在普通数据集上性能不降，表明方法的针对性有效。'",
          score: 95,
        },
        {
          question: "SAC在高维连续状态空间的处理",
          answer: "PCA降维到低维隐空间，限制动作空间为局部调整",
          evaluation: "良好——工程化处理思路合理，维度分析清晰",
          expression_advice: "可以讨论降维后信息损失的处理，以及是否尝试过其他表示方法（如卷积特征提取）。",
          suggested_answer: "更完整的回答：除PCA外，也可以考虑卷积神经网络直接提取空间特征作为状态表示；动作空间可以用分层策略（high-level选区域，low-level调相位）进一步降低复杂度。",
          score: 82,
        },
        {
          question: "手撕代码：两数之和",
          answer: "哈希表实现，一次通过，O(n)时间O(n)空间，代码简洁正确",
          evaluation: "出色——思路清晰，直接给出最优解，代码可读性强",
          expression_advice: "可以主动说明边界情况（数组为空、无解），展示工程思维。",
          suggested_answer: "完整工程版本还应加：输入验证（`if not nums: return []`）、注释，以及一句话说明为何选哈希表而非暴力O(n²)。",
          score: 97,
        },
      ],
      strengths: ["技术理解深入，能从方法论层面阐述研究创新", "量化数据准确，科研汇报能力突出", "算法题一次AC，编程基础扎实", "逻辑表达清晰，条理分明"],
      improvements: ["可以更主动展示批判性思维（指出方法局限）", "部分回答可以补充边界情况和替代方案", "算法题完整工程版本需加输入验证"],
      overallScore: "A — 表现优秀，综合实力突出，强烈推荐",
      expression_summary: "候选人整体表达逻辑严谨，技术术语使用准确；量化数据充分，说服力强；建议练习主动提出方法局限性和未来改进方向，展示更成熟的研究思维。",
    },
  },
];
